[server]
host = "0.0.0.0" # Optional, default 0.0.0.0
port = 554 # Optional, default 554

# The stream for this h264 camera would be made available at rtsp://<host>:<port>/front_deck
[stream.front_deck]
# Accepts string "<host>[:port]", port defaults to 1264
# Currently only accepts IPv4 addresses for the host portion
addr = "192.168.1.254:1264"
#addr = "192.168.1.254" # works just as well
